function [Planet] = bodysort()
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
     Planet = struct(...    
       'name',' '    ...    
      ,'mass',0      ...    Mass                [kg] 
      ,'radius',0    ...    Radius @ Equator    [m]
      ,'P1',[0 0 0]  ...    
      ,'P11',[0 0 0] ...    
      ,'P2',[0 0 0]  ...    
      ,'P21',[0 0 0] ...    
      ,'V1',[0 0 0]  ...    
      ,'V11',[0 0 0] ...    
      ,'V2',[0 0 0]  ...    
      ,'V21',[0 0 0] ...    
      ,'Path1',0     ...    
      ,'Path2',0     ...    
      ,'a',0         ...    
      ,'e',0         ...    
      ,'i',0         ...    
      ,'Omega',0     ...    
      ,'w',0         ...    
      ,'Vo1',0       ...    
      ,'Vo2',0       ...    
      ,'H',[0 0 0]   ...    
      ,'N',[0 0 0]   ...      
      ,'EV',[0 0 0]  ...  
      );
      end
